version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./dist:/var/www/html
    depends_on:
      - db
    links:
      - db
    ports:
      - "80:80"
  db:
    image: mysql:5.7.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "sample"
      MYSQL_DATABASE: "sample"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
